post:
  tags:
    - Configuration
  parameters:
    - name: Authentication
      in: header
      required: true
      schema:
        type: string
        default: >-
          c3B2LTItUEFnOVRmWjg5UVZqWjVZSDhVWkZoc3RrRHBHbmNkSkNxUUI4R2NTc1NxbXVrYjM0R0RBQVVETDlDNDdGN0Y4bg==
  requestBody:
    content:
      application/json-patch+json:
        schema:
          $ref: ..\components\schemas\ChangeUiThemeInput.yaml
      application/json:
        schema:
          $ref: ..\components\schemas\ChangeUiThemeInput.yaml
      text/json:
        schema:
          $ref: ..\components\schemas\ChangeUiThemeInput.yaml
      application/*+json:
        schema:
          $ref: ..\components\schemas\ChangeUiThemeInput.yaml
  responses:
    '200':
      description: Success
